### ISSUE TITLE
Validate OnboardingCommands

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/onboarding-android#3]
Validar que el funcionamiento es el correcto y que la explicación en onboarding-android, sea correcta: 

Rama **doc/onboarding-commands** 

https://github.com/alice-biometrics/onboarding-android/tree/doc/onboarding-commands

Tengo dudas de que funcione el addDocument. Ya que ahora necesitamos el tipo y el issuingCountry.

**Comment by fgsalomon** [comment]
Me encargo yo.

**Comment by fgsalomon** [comment]
> Tengo dudas de que funcione el addDocument. Ya que ahora necesitamos el tipo y el issuingCountry.

Pues en la demo funciona correctamente, se debió actualizar en su día.

La doc está ok. Añadí unos parámetros que faltaban en el `addDocument`.
